version: '1'
services:
  database:
    image: "postgres"
    restart: always
    env_file:
      - database.env
    ports:
      - '2345:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
